############################################################
# MAKEFILE for ICP course, 2014
############################################################
#	Author:		David Kaspar (aka Dee'Kej), 3BIT
#						BUT FIT, Czech Republic
#
# E-mails:	xkaspa34@stud.fit.vutbr.cz
#
# Date:			23-04-2014
############################################################

############################################################
# Default rule for creating all required files:
############################################################

all:
	@$(MAKE) -C src/server
	@$(MAKE) -C src/client

############################################################
# Other useful stuff:
############################################################

# Rule to mark "false-positive" targets in project folder.
.PHONY: run doxygen pack clean clean-all

run:

doxygen:

pack:


# Remove object files generated during compiling.
clean:
	@$(MAKE) clean -C src/server
	@$(MAKE) clean -C src/client

# Remove all files generated by doxygen:
clean-doc:
	@echo "make[1]: Removing doxygen documentation"
	@rm -rf doc/*

# Remove all generated files:
clean-all: clean-doc
	@$(MAKE) clean-all -C src/server
	@$(MAKE) clean-all -C src/client
